# Generated by Django 5.2.8 on 2025-12-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_content_imagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='title',
            field=models.CharField(max_length=5000),
        ),
    ]
