# Generated by Django 5.2.8 on 2025-12-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='avatarlink',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='userID',
            new_name='username',
        ),
    ]
