# Generated by Django 5.2.8 on 2025-12-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_profile_patronymic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('worker', 'Работник'),)},
        ),
    ]
