# Generated by Django 5.2.8 on 2025-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('n', 'Новая заявка'), ('w', 'Принята в работу'), ('c', 'Выполнена'), ('r', 'Отклонена')], default='n', max_length=1)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
