# Generated by Django 5.2.8 on 2025-12-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_application_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('worker', 'Работник'), ('user', 'Пользователь'))},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='category',
            new_name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.CharField(blank=True, choices=[('3', '3D Дизайн'), ('2', '2D Дизайн'), ('e', 'Эскиз'), ('l', 'Логотип')], default='n', max_length=1),
        ),
    ]
