# Generated by Django 6.0 on 2025-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_application_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='categories',
            field=models.CharField(choices=[('3', '3D Дизайн'), ('2', '2D Дизайн'), ('e', 'Эскиз'), ('l', 'Логотип')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('n', 'Новая заявка'), ('w', 'Принята в работу'), ('c', 'Выполнена'), ('r', 'Отклонена')], default='n', max_length=1),
        ),
    ]
