# Generated by Django 6.0 on 2025-12-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_category_alter_application_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
