# Generated by Django 5.2.8 on 2025-12-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_application_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_char',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
