# Generated by Django 5.2.8 on 2025-12-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='image_content',
            new_name='ImageContent',
        ),
    ]
