# Generated by Django 5.2.8 on 2025-12-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_imagecontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='title',
            field=models.TextField(),
        ),
    ]
