# Generated by Django 5.2.8 on 2025-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_imagecontent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecontent',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagecontent',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
